package poke;

public class Pokedex {
            
            public static void DexJava(){
            
             System.out.print("#001 Bulbasaur Tipo: Planta.\n#002 Ivysaur Tipo: Planta.\n#003 Venusaur Tipo: Planta e Veneno.\n#004 Charmander Tipo: Fogo.\n#005 Charmeleon Tipo: Fogo.\n#006 Charizard Tipo: Fogo e Vento.\n#007 Squirtle Tipo: Água.\n#008 Wartortle Tipo: Água.\n#009  Blastoise Tipo: Água.\n#010 Caterpie Tipo: Inseto.\n#011 Metapod Tipo: Inseto.\n#012 Butterfree Tipo: Inseto e Voador.\n#013 Weedle Tipo: Inseto e Veneno.\n#014 Kakuna Tipo: Inseto e Veneno.\n#015 Beedrill Tipo: Inseto e Veneno.\n#016 Pidgey Tipo: Normal e Voador.\n#017 Pidgeotto Tipo: Normal e Voador.\n#018 Pidgeot Tipo: Normal e Voador.\n#019 Rattata Tipo: Normal.\n#020 Raticate Tipo: Normal.\n#021 Spearow Tipo: Normal e Voador.\n#022 Fearow Tipo: Normal e Voador\n#023 Ekans Tipo: Veneno.\n#024 Arbok Tipo: Veneno.\n#025 Pikachu Tipo: Elétrico.\n#026 Raichu Tipo: Elétrico.\n#027 Sandshrew Tipo: Terrestre.\n#028 Sandslash Tipo: Terrestre.\n#029 Nidoran Fêmea Tipo: Veneno.\n#030 Nidorina Tipo: Veneno.\n");
             
             System.out.print("#031 Nidoqueen Tipo: Veneno e Terrestre.\n#032 Nidoran Macho Tipo: Veneno.\n#033 Nidorino Tipo: Veneno.\n#034 Nidoking Tipo: Veneno e Terrestre.\n#035 Clefairy Tipo: Fada.\n#036 Clefable Tipo: Fada.\n#037 Vulpix Tipo: Fogo.\n#039 Ninetales Tipo: Fago.\n#040 Jigglypuff Tipo: Normal e Fada.\n#041 Wigglytuff Tipo: Normal e Fada.\n#042 Zubat Tipo: Veneno e Voador.\n#043 Oddish  Tipo: Veneno e Planta.\n#044 Gloom Tipo: Veneno e Planta.\n#045 Vileplume Tipo: Veneno e Planta.\n#046 Paras Tipo: Inseto e Planta.\n#047 Parasect Tipo: Inseto e Planta.\n#048 Venonat Tipo: Veneno e Inseto.\n#049 Venomoth Tipo: Veneno e Planta.\n#050 Diglett Tipo: Terrestre.\n#051 Dugtrio Tipo: Terrestre.\n#052 Meowth Tipo: Normal.\n#053 Persian Tipo: Normal.\n#054 Psyduck Tipo: Água.\n#055 Golduck Tipo: Água.\n#056 Mankey Tipo: Lutador.\n#057 Primeape Tipo: Lutador.\n#058 Growlthe Tipo: Fogo.\n#059 Arcanine Tipo: Fogo.\n#060 Poliwag Tipo: Água.\n");
             
             System.out.print("#061 Poliwhirl Tipo: Água.\n#062 Poliwrath Tipo: Água e Lutador.\n#063 Abra Tipo: Psíquico.\n#064 kadabra Tipo: Psíquico.\n#065 Alakazam Tipo: Psíquico.\n#066 Machop Tipo: Lutador.\n#067 Machoke Tipo: Lutador.\n#068 Machamp Tipo: Lutador.\n#069 Bellsprout Tipo: Planta e Veneno.\n#070 Weepinbell Tipo: Planta e Veneno.\n#071 Victreebel Tipo: Planta e Veneno.\n#072 Tentacool Tipo: Água e Veneno.\n#073 Tentacruel Tipo: Água e Veneno.\n#074 Geodude Tipo: Pedra e Terrestre.\n#075 Graveler Tipo: Pedra e Terrestre.\n#076 Golem Tipo: Pedra e Terrestre.\n#077 Ponyta Tipo: Fogo.\n#078 Rapidash Tipo: Fogo.\n#079 Slowpoke Tipo: Água e Psíquico.\n#080 Slowbro Tipo: Água e Psíquico.\n#081 Magnemite Tipo: Elétrico e Aço.\n#082 Magneton Tipo: Elétrico e Aço.\n#083 Farfetch'd Tipo: Normal e voador.\n#084 Doduo Tipo: Normal e voador.\n#085 Dodrio Tipo: Normal e voador.\n#086 Seel Tipo: Água.\n#087 Dewgong Tipo: Água e Gelo.\n#088 Grimer Tipo: Veneno.\n#089 Muk Tipo: Veneno.\n#090 Shellder Tipo: Água.\n");
             
             System.out.print("#091 Gastly Tipo: Fantasma e Veneno\n#92 Cloyster Tipo: Água e Gelo\n#093 Haunter Tipo: Fantasma e Veneno\n#094 Gengar Tipo: Fantasma e Veneno\n#095 Onix Tipo: Pedra e Terrestre\n#096 Drowzee Tipo: Psíquico\n#097 Hypno Tipo: Psíquico\n#098 Krabby Tipo: Água\n#099 Kingler Tipo: Água\n#100 Voltorb Tipo: Elétrico\n#101 Electrode Tipo: Elétrico\n#102 Exeggcute Tipo: Planta e Psíquico\n#103 Exeggutor Tipo: Planta e Psíquico\n#104 Cubone Tipo: Terrestre\n#105 Marowak Tipo: Terrestre\n#106 Hitmonlee Tipo: Lutador\n#107 Hitmonchan Tipo: Lutador\n#108 Lickitung Tipo: Normal\n#109 Koffing Tipo: Veneno\n#110 Weezing Tipo: Veneno\n#111 Rhyhorn Tipo: Terrestre e Pedra\n#112 Rhydon Tipo: Terrestre e Pedra\n#113 Chansey Tipo: Normal\n#114 Tangela Tipo: Planta\n#115 Kangaskhan Tipo: Normal\n#116 Horsea Tipo: Água\n#117 Seadra Tipo: Água\n#118 Goldeen Tipo: Água\n#119 Seaking Tipo: Água\n#120 Staryu Tipo: Água\n");
              
              System.out.println("#121 Starmie Tipo: Água e Psíquico\n#122 Mr.Mime Tipo: Psíquico e Fada\n#123 Scyther Tipo: Inseto e Voador\n#124 Jynx Tipo: Gelo e Psíquico\n#125 Electabuzz Tipo: Elétrico\n#126 Magmar Tipo: Fogo\n#127 Pinsir Tipo: Inseto\n#128 Tauros Tipo: Normal\n#129 Magikarp Tipo: água\n#130 Gyarados Tipo: Água e Voador\n#131 Lapras Tipo: Água e Gelo\n#132 Ditto Tipo: Normal\n#133 Eevee Tipo: Normal\n#134 Vaporeon Tipo: Água\n#135 Jolteon Tipo: Elétrico\n#136 Flareon Tipo: Fogo\n#137 Porygon Tipo: Normal\n#138 Omanyte Tipo: Pedra e água\n#139 Omaster Tipo: Pedra e água\n#140 Kabuto Tipo: Pedra e Água\n#141 Kabutops Tipo: Pedra e Água\n#142 Aerodactyl Tipo: Pedra e Voador\n#143 Snorlax Tipo: Normal\n#144 ARTICUNO Tipo: Gelo e Voador LENDÁRIO\n#145 ZAPDOS Tipo: Elétrico e Voador LENDÁRIO\n#146 MOLTRES Tipo: Fogo e Voador LENDÁRIO\n#147 Dratini Tipo: Dragão\n#148 Dragonair Tipo: Dragão\n#149 Dragonite Tipo: Dragão e Voador\n#150 MEWTWO Tipo: Psíquico LENDÁRIO\n#150 MEW Tipo: Psíquico LENDÁRIO\n#151 Meltan Tipo: Aço\n#152 Melmetal Tipo: Aço\n");
              
            }

}
